[package]
name = "cosmian_kms_python"
version = "4.4.1"
authors = ["Hugo Rosenkranz-Costa <hugo.rosenkranz@cosmian.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "cosmian_kms"

[dependencies]
cloudproof = { workspace = true }
cosmian_kmip = { path = "../kmip" }
cosmian_kms_client = { path = "../client" }
cosmian_kms_utils = { path = "../utils" }
leb128 = { workspace = true }
pyo3 = { version = "0.18", features = ["extension-module", "abi3", "abi3-py37", "generate-import-lib"] }
pyo3-asyncio = { version = "0.18", features = ["tokio-runtime"] }
serde_json = { workspace = true }

# Added with build.rs to fix build issues on MacOS
# see https://github.com/PyO3/pyo3/issues/1857
[build-dependencies]
pyo3-build-config = "0.18"
